"""
udp_latency_analyzer.py - Scientific-Grade EEW UDP Latency Evaluation Tool
===========================================================================
Receives EEW sensor UDP packets and computes end-to-end One-Way Delay (OWD)
from packet sample-origin timestamp to OS receive time.

Usage
-----
  python udp_latency_analyzer.py               # Live capture, Ctrl+C to stop
  python udp_latency_analyzer.py --duration 300  # Fixed 300-second run
  python udp_latency_analyzer.py --selftest      # Loopback self-test
  python udp_latency_analyzer.py --no-dashboard  # Plain stdout mode

Requirements
------------
  pip install numpy matplotlib scipy
  On Windows for the dashboard: pip install windows-curses

Methodology
-----------
  OWD = t_recv(PC) - packet_timestamp(RPi)
  packet_timestamp is the NTP-disciplined UTC epoch of the FIRST sample
  in the packet, generated by the Software PLL in sensor.py.

  IMPORTANT: Both clocks must be NTP-synchronized.
    Windows: w32tm /query /status
    Linux:   chronyc tracking

Output files
------------
  udp_latency_data_<TIMESTAMP>.csv     - raw per-packet measurements
  udp_latency_report_<TIMESTAMP>.txt   - human-readable summary report
  udp_latency_<TIMESTAMP>_owd.png      - OWD time-series
  udp_latency_<TIMESTAMP>_hist.png     - OWD histogram + fitted PDF
  udp_latency_<TIMESTAMP>_cdf.png      - OWD empirical CDF
  udp_latency_<TIMESTAMP>_jitter.png   - Jitter time-series

Packet Format (EEW Datacast / Raspberry Shake compatible)
----------------------------------------------------------
  {'ENZ', <packet_timestamp>, <s1>, <s2>, ..., <s25>}
  or legacy Python list:
  ['ENZ', <packet_timestamp>, <s1>, <s2>, ..., <s25>]
"""

import argparse
import ast
import collections
import csv
import math
import os
import queue
import socket
import subprocess
import sys
import threading
import time
from datetime import datetime, timezone

import numpy as np

# Optional imports
try:
    import curses as _curses
    _CURSES_AVAILABLE = True
except ImportError:
    _CURSES_AVAILABLE = False

try:
    from scipy import stats as _scipy_stats
    _SCIPY_AVAILABLE = True
except ImportError:
    _SCIPY_AVAILABLE = False

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    _MPL_AVAILABLE = True
except ImportError:
    _MPL_AVAILABLE = False

# Constants
EXPECTED_INTERVAL_S      = 0.250   # 25 samples @ 100 SPS per packet
LOSS_THRESHOLD_S         = 0.600   # gap > this -> packet(s) lost
JITTER_ALPHA             = 0.0625  # 1/16 - RFC 3550 EWMA smoothing factor
ROLLING_WINDOW_S         = 60.0    # statistics window in seconds
HISTOGRAM_BINS           = 40      # OWD histogram buckets
CLOCK_WARN_THRESHOLD_MS  = 50.0    # warn if NTP offset > this ms
CHANNEL_NAMES            = ('ENZ', 'ENN', 'ENE')


# ── Data structures ──────────────────────────────────────────────────────────

class PacketRecord:
    """One captured UDP packet full measurement record."""
    __slots__ = (
        'seq', 'recv_utc', 'packet_ts', 'channel',
        'owd_ms', 'jitter_ms', 'n_samples',
        'clock_offset_ms', 'is_loss_gap',
    )
    def __init__(self, seq, recv_utc, packet_ts, channel,
                 owd_ms, jitter_ms, n_samples, clock_offset_ms, is_loss_gap=False):
        self.seq             = seq
        self.recv_utc        = recv_utc
        self.packet_ts       = packet_ts
        self.channel         = channel
        self.owd_ms          = owd_ms
        self.jitter_ms       = jitter_ms
        self.n_samples       = n_samples
        self.clock_offset_ms = clock_offset_ms
        self.is_loss_gap     = is_loss_gap


class RollingStats:
    """O(1) rolling window statistics using a deque."""
    def __init__(self, window_s=ROLLING_WINDOW_S):
        self.window_s = window_s
        self._data    = collections.deque()

    def add(self, ts, value):
        self._data.append((ts, value))
        cutoff = ts - self.window_s
        while self._data and self._data[0][0] < cutoff:
            self._data.popleft()

    def values(self):
        return [v for _, v in self._data]

    def count(self):
        return len(self._data)

    def compute(self):
        vals = self.values()
        if not vals:
            return {'mean': 0.0, 'std': 0.0, 'min': 0.0,
                    'max': 0.0, 'p50': 0.0, 'p95': 0.0, 'p99': 0.0, 'n': 0}
        a = np.array(vals, dtype=np.float64)
        return {
            'mean': float(np.mean(a)),
            'std':  float(np.std(a, ddof=1)) if len(a) > 1 else 0.0,
            'min':  float(np.min(a)),
            'max':  float(np.max(a)),
            'p50':  float(np.percentile(a, 50)),
            'p95':  float(np.percentile(a, 95)),
            'p99':  float(np.percentile(a, 99)),
            'n':    len(a),
        }


# ── NTP clock utilities ──────────────────────────────────────────────────────

def get_ntp_offset_ms():
    """Return local clock offset from NTP in ms, or None on failure."""
    try:
        if sys.platform == 'win32':
            result = subprocess.run(
                ['w32tm', '/query', '/status'],
                capture_output=True, text=True, timeout=3
            )
            for line in result.stdout.splitlines():
                if 'Phase Offset' in line:
                    parts = line.split(':', 1)
                    if len(parts) > 1:
                        val_str = parts[1].strip().split('s')[0].strip()
                        try:
                            return float(val_str) * 1000.0
                        except ValueError:
                            pass
        else:
            result = subprocess.run(
                ['chronyc', 'tracking'],
                capture_output=True, text=True, timeout=3
            )
            for line in result.stdout.splitlines():
                if 'System time' in line:
                    parts = line.split(':', 1)
                    if len(parts) > 1:
                        val_parts = parts[1].strip().split()
                        if val_parts:
                            try:
                                val = float(val_parts[0]) * 1000.0
                                if 'slow' in parts[1]:
                                    val = -val
                                return val
                            except ValueError:
                                pass
    except Exception:
        pass
    return None


# ── Packet parser ────────────────────────────────────────────────────────────

def parse_eew_packet(raw):
    """Parse an EEW sensor UDP packet.

    Supports Raspberry Shake Datacast format:
      {'ENZ', 1722000000.123456, s1, s2, ..., s25}
    and legacy Python list format:
      ['ENZ', 1722000000.123456, s1, s2, ..., s25]

    Returns (channel, packet_ts, samples) or None on parse error.
    """
    try:
        decoded = raw.decode('utf-8', errors='replace').strip()
        normalized = decoded
        if normalized.startswith('{') and normalized.endswith('}'):
            normalized = '[' + normalized[1:-1] + ']'
        packet = ast.literal_eval(normalized)
        if not isinstance(packet, (list, tuple)) or len(packet) < 3:
            return None
        channel   = str(packet[0]).strip("' \"")
        packet_ts = float(packet[1])
        samples   = packet[2:]
        return channel, packet_ts, samples
    except Exception:
        return None


# ── Self-test sender ─────────────────────────────────────────────────────────

def _selftest_sender(port, stop_event):
    """Background thread: sends fake EEW packets to localhost for loopback testing."""
    sock      = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    interval  = EXPECTED_INTERVAL_S
    next_send = time.time() + 0.5
    seq       = 0
    print(f"[SELFTEST] Sending fake packets to 127.0.0.1:{port} every {interval*1000:.0f} ms")
    while not stop_event.is_set():
        now = time.time()
        remaining = next_send - now
        if remaining > 0:
            time.sleep(remaining)
        packet_ts   = next_send - interval
        samples     = [round(0.01 * math.sin(2 * math.pi * seq * 0.01), 6)] * 25
        samples_str = ', '.join(str(s) for s in samples)
        pkt         = "{'ENZ', " + f"{packet_ts:.6f}" + ", " + samples_str + "}"
        try:
            sock.sendto(pkt.encode('utf-8'), ('127.0.0.1', port))
        except OSError:
            pass
        next_send += interval
        seq += 1
    sock.close()


# ── CSV writer ───────────────────────────────────────────────────────────────

CSV_FIELDNAMES = [
    'seq', 'recv_utc', 'packet_ts', 'channel',
    'owd_ms', 'jitter_ms', 'n_samples',
    'clock_offset_ms', 'is_loss_gap',
]

def open_csv(filepath):
    fh     = open(filepath, 'w', newline='', buffering=1, encoding='utf-8')
    writer = csv.DictWriter(fh, fieldnames=CSV_FIELDNAMES)
    writer.writeheader()
    return fh, writer

def write_csv_row(writer, r):
    writer.writerow({
        'seq':              r.seq,
        'recv_utc':         f"{r.recv_utc:.6f}",
        'packet_ts':        f"{r.packet_ts:.6f}",
        'channel':          r.channel,
        'owd_ms':           f"{r.owd_ms:.3f}",
        'jitter_ms':        f"{r.jitter_ms:.3f}",
        'n_samples':        r.n_samples,
        'clock_offset_ms':  f"{r.clock_offset_ms:.3f}" if r.clock_offset_ms is not None else 'N/A',
        'is_loss_gap':      1 if r.is_loss_gap else 0,
    })


# ── Report generator ─────────────────────────────────────────────────────────

def generate_text_report(records, session_start, session_end, filepath, args):
    """Write a human-readable scientific text report."""
    owd_vals   = np.array([r.owd_ms for r in records if not r.is_loss_gap], dtype=np.float64)
    n_total    = len(records)
    n_loss     = sum(1 for r in records if r.is_loss_gap)
    n_received = n_total - n_loss
    duration   = session_end - session_start
    loss_rate  = (n_loss / n_total * 100) if n_total > 0 else 0.0

    with open(filepath, 'w', encoding='utf-8') as f:
        def w(line=''):
            f.write(line + '\n')

        w("=" * 72)
        w("  EEW UDP LATENCY EVALUATION -- SCIENTIFIC REPORT")
        w("=" * 72)
        w(f"  Generated : {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
        w(f"  Station   : {args.ip}:{args.port}")
        w(f"  Duration  : {duration:.1f} s  ({duration/60:.2f} min)")
        w(f"  Mode      : {'SELFTEST (loopback)' if args.selftest else 'LIVE capture'}")
        w()
        w("-" * 72)
        w("  PACKET STATISTICS")
        w("-" * 72)
        w(f"  Total packets logged      : {n_total}")
        w(f"  Packets received          : {n_received}")
        w(f"  Packets lost (gap events) : {n_loss}")
        w(f"  Packet loss rate          : {loss_rate:.4f} %")
        w()

        if len(owd_vals) >= 2:
            w("-" * 72)
            w("  ONE-WAY DELAY (OWD) STATISTICS  [ms]")
            w("-" * 72)
            w(f"  N (valid packets)  : {len(owd_vals)}")
            w(f"  Mean               : {np.mean(owd_vals):.3f} ms")
            w(f"  Std Dev            : {np.std(owd_vals, ddof=1):.3f} ms")
            w(f"  Minimum            : {np.min(owd_vals):.3f} ms")
            w(f"  Maximum            : {np.max(owd_vals):.3f} ms")
            w(f"  Median (P50)       : {np.percentile(owd_vals, 50):.3f} ms")
            w(f"  P75                : {np.percentile(owd_vals, 75):.3f} ms")
            w(f"  P95                : {np.percentile(owd_vals, 95):.3f} ms")
            w(f"  P99                : {np.percentile(owd_vals, 99):.3f} ms")
            w(f"  P99.9              : {np.percentile(owd_vals, 99.9):.3f} ms")
            w()

            if _SCIPY_AVAILABLE:
                try:
                    pos = owd_vals[owd_vals > 0]
                    if len(pos) > 10:
                        shape, loc, scale = _scipy_stats.lognorm.fit(pos, floc=0)
                        ks_stat, ks_p = _scipy_stats.kstest(pos, 'lognorm', args=(shape, loc, scale))
                        w("-" * 72)
                        w("  DISTRIBUTION FIT -- Log-Normal  (OWD > 0 ms)")
                        w("-" * 72)
                        w(f"  Shape (sigma)      : {shape:.4f}")
                        w(f"  Scale (exp(mu))    : {scale:.4f} ms")
                        w(f"  KS statistic       : {ks_stat:.4f}")
                        w(f"  KS p-value         : {ks_p:.4f}  "
                          f"({'good fit' if ks_p > 0.05 else 'poor fit -- consider Weibull'})")
                        w()
                except Exception:
                    pass

        w("-" * 72)
        w("  DELAY BUDGET INTERPRETATION")
        w("-" * 72)
        w("  Expected delay components:")
        w("    - Firmware buffer accumulation  : 0 - 250 ms  (25 samples @ 100 SPS)")
        w("    - ZeroTier P2P tunnel           : 5 - 50 ms   (typical LAN punch-through)")
        w("    - ZeroTier relay (DERP)         : 30 - 200 ms (if direct path blocked)")
        w("    - OS receive queue jitter       : 0 - 10 ms")
        w("    - NTP clock offset bias         : varies (check w32tm /query /status)")
        w()

        if len(owd_vals) >= 2:
            mean_owd = np.mean(owd_vals)
            if mean_owd < 50:
                w("  ASSESSMENT: Excellent -- mean OWD < 50 ms. Likely ZeroTier P2P path.")
            elif mean_owd < 150:
                w("  ASSESSMENT: Good -- mean OWD 50-150 ms. ZeroTier relay may be active.")
            elif mean_owd < 350:
                w("  ASSESSMENT: Moderate -- mean OWD 150-350 ms. Includes firmware buffering.")
            else:
                w("  ASSESSMENT: High latency. Investigate NTP clock sync and ZeroTier path.")
        w()
        w("-" * 72)
        w("  CLOCK SYNC NOTE")
        w("-" * 72)
        w("  OWD = t_receive(PC) - packet_timestamp(RPi).")
        w("  Clock offset between PC and RPi introduces a constant bias in all OWD values.")
        w("  Run clock_offset_probe.py for an NTP-independent offset estimate.")
        w()
        w("=" * 72)

    print(f"  Report saved -> {filepath}")


# ── Matplotlib figures ────────────────────────────────────────────────────────

PLOT_STYLE = {
    'figure.facecolor': '#0d1117',
    'axes.facecolor':   '#161b22',
    'axes.edgecolor':   '#30363d',
    'axes.labelcolor':  '#c9d1d9',
    'xtick.color':      '#8b949e',
    'ytick.color':      '#8b949e',
    'text.color':       '#c9d1d9',
    'grid.color':       '#21262d',
    'grid.linestyle':   '--',
    'grid.linewidth':   0.5,
    'font.family':      'DejaVu Sans',
}

def _apply_style():
    for k, v in PLOT_STYLE.items():
        plt.rcParams[k] = v


def generate_figures(records, session_start, session_end, prefix):
    """Generate all matplotlib figures and save to disk."""
    if not _MPL_AVAILABLE:
        print("  [WARN] matplotlib not installed -- skipping figures.")
        return

    _apply_style()
    valid   = [r for r in records if not r.is_loss_gap]
    owd_ms  = np.array([r.owd_ms     for r in valid], dtype=np.float64)
    jit_ms  = np.array([r.jitter_ms  for r in valid], dtype=np.float64)
    t_rel   = np.array([r.recv_utc - session_start for r in valid], dtype=np.float64)

    if len(owd_ms) < 2:
        print("  [WARN] Not enough data for figures.")
        return

    ACCENT  = '#58a6ff'
    ACCENT2 = '#f0883e'
    ACCENT3 = '#3fb950'
    RED     = '#f85149'

    # 1. OWD Time Series
    fig, ax = plt.subplots(figsize=(12, 4), dpi=120)
    ax.scatter(t_rel, owd_ms, s=2, alpha=0.5, color=ACCENT, label='OWD per packet', rasterized=True)
    if len(owd_ms) >= 30:
        kernel  = np.ones(30) / 30
        rolling = np.convolve(owd_ms, kernel, mode='valid')
        ax.plot(t_rel[29:], rolling, color=ACCENT2, lw=1.5, label='30-packet rolling mean')
    for pct, lbl, clr in [(50, 'P50', ACCENT3), (95, 'P95', ACCENT2), (99, 'P99', RED)]:
        val = np.percentile(owd_ms, pct)
        ax.axhline(val, color=clr, ls=':', lw=1.0, label=f'{lbl} = {val:.1f} ms')
    ax.set_xlabel('Time since capture start (s)')
    ax.set_ylabel('One-Way Delay (ms)')
    ax.set_title('EEW Sensor UDP -- One-Way Delay Time Series', fontsize=13, pad=10)
    ax.legend(fontsize=8, loc='upper right')
    ax.grid(True)
    ax.set_xlim(0, max(t_rel))
    fig.tight_layout()
    p = f"{prefix}_owd.png"
    fig.savefig(p, bbox_inches='tight')
    plt.close(fig)
    print(f"  Figure -> {p}")

    # 2. OWD Histogram
    fig, ax = plt.subplots(figsize=(8, 5), dpi=120)
    clipped = np.clip(owd_ms, 0, np.percentile(owd_ms, 99.5))
    ax.hist(clipped, bins=HISTOGRAM_BINS, color=ACCENT, alpha=0.75, density=True,
            edgecolor='#161b22', label='Empirical density')
    if _SCIPY_AVAILABLE and len(clipped) > 10:
        try:
            pos = clipped[clipped > 0]
            if len(pos) > 10:
                shape, loc, scale = _scipy_stats.lognorm.fit(pos, floc=0)
                x_fit = np.linspace(pos.min(), pos.max(), 500)
                ax.plot(x_fit, _scipy_stats.lognorm.pdf(x_fit, shape, loc, scale),
                        color=ACCENT2, lw=2, label='Log-normal fit')
        except Exception:
            pass
    for pct, lbl, clr in [(50, 'P50', ACCENT3), (95, 'P95', ACCENT2), (99, 'P99', RED)]:
        val = np.percentile(owd_ms, pct)
        ax.axvline(val, color=clr, ls='--', lw=1.2, label=f'{lbl} = {val:.1f} ms')
    ax.set_xlabel('One-Way Delay (ms)')
    ax.set_ylabel('Probability density')
    ax.set_title('EEW UDP OWD Distribution (clipped at P99.5)', fontsize=13, pad=10)
    ax.legend(fontsize=8)
    ax.grid(True)
    fig.tight_layout()
    p = f"{prefix}_hist.png"
    fig.savefig(p, bbox_inches='tight')
    plt.close(fig)
    print(f"  Figure -> {p}")

    # 3. Empirical CDF
    fig, ax = plt.subplots(figsize=(8, 5), dpi=120)
    sorted_owd = np.sort(owd_ms)
    cdf = np.arange(1, len(sorted_owd) + 1) / len(sorted_owd)
    ax.plot(sorted_owd, cdf * 100, color=ACCENT, lw=2)
    for pct, lbl, clr in [(50, 'P50', ACCENT3), (95, 'P95', ACCENT2), (99, 'P99', RED)]:
        val = np.percentile(owd_ms, pct)
        ax.axvline(val, color=clr, ls='--', lw=1.0, label=f'{lbl} = {val:.1f} ms')
        ax.axhline(pct, color=clr, ls=':', lw=0.7, alpha=0.5)
    ax.set_xlabel('One-Way Delay (ms)')
    ax.set_ylabel('Cumulative Probability (%)')
    ax.set_title('EEW UDP OWD -- Empirical CDF', fontsize=13, pad=10)
    ax.legend(fontsize=8)
    ax.set_ylim(0, 101)
    ax.grid(True)
    fig.tight_layout()
    p = f"{prefix}_cdf.png"
    fig.savefig(p, bbox_inches='tight')
    plt.close(fig)
    print(f"  Figure -> {p}")

    # 4. Jitter Time Series
    fig, ax = plt.subplots(figsize=(12, 3), dpi=120)
    ax.plot(t_rel, jit_ms, color=ACCENT2, lw=0.8, alpha=0.8, label='EWMA Jitter (RFC 3550)')
    ax.axhline(np.mean(jit_ms), color=ACCENT3, ls='--', lw=1.0,
               label=f'Mean = {np.mean(jit_ms):.2f} ms')
    ax.set_xlabel('Time since capture start (s)')
    ax.set_ylabel('Jitter (ms)')
    ax.set_title('EEW UDP -- Packet Delay Variation (Jitter)', fontsize=13, pad=10)
    ax.legend(fontsize=8)
    ax.grid(True)
    ax.set_xlim(0, max(t_rel))
    fig.tight_layout()
    p = f"{prefix}_jitter.png"
    fig.savefig(p, bbox_inches='tight')
    plt.close(fig)
    print(f"  Figure -> {p}")


# ── Histogram bar ─────────────────────────────────────────────────────────────

def _build_histogram_bar(values, width=30, max_val=None):
    if not values:
        return ' ' * width, 0.0, 1.0
    a    = np.array(values, dtype=np.float64)
    vmin = np.min(a)
    vmax = max_val if max_val is not None else np.percentile(a, 99)
    if vmax <= vmin:
        vmax = vmin + 1.0
    bins = np.linspace(vmin, vmax, width + 1)
    counts, _ = np.histogram(a, bins=bins)
    bar_max = max(counts.max(), 1)
    chars = ' \u2581\u2582\u2583\u2584\u2585\u2586\u2587\u2588'
    bar_str = ''.join(chars[min(int(c / bar_max * 8), 8)] for c in counts)
    return bar_str, vmin, vmax


# ── Curses dashboard ──────────────────────────────────────────────────────────

def run_dashboard(stdscr, records, stop_event, rx_queue, args, session_start, clock_offset_ms):
    import curses
    curses.curs_set(0)
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_CYAN,   -1)
    curses.init_pair(2, curses.COLOR_GREEN,  -1)
    curses.init_pair(3, curses.COLOR_YELLOW, -1)
    curses.init_pair(4, curses.COLOR_RED,    -1)
    curses.init_pair(5, curses.COLOR_WHITE,  -1)
    curses.init_pair(6, curses.COLOR_MAGENTA,-1)

    C_TITLE = curses.color_pair(1) | curses.A_BOLD
    C_GOOD  = curses.color_pair(2)
    C_WARN  = curses.color_pair(3)
    C_ERR   = curses.color_pair(4)
    C_LABEL = curses.color_pair(5)
    C_HIST  = curses.color_pair(6)

    rolling      = RollingStats(ROLLING_WINDOW_S)
    jitter_ema   = 0.0
    n_received   = 0
    n_loss       = 0
    last_ts      = {}
    seq          = 0

    stdscr.nodelay(True)

    while not stop_event.is_set():
        # Drain queue
        while True:
            try:
                recv_utc, raw = rx_queue.get_nowait()
            except queue.Empty:
                break
            parsed = parse_eew_packet(raw)
            if parsed is None:
                continue
            channel, packet_ts, samples = parsed
            owd_ms = (recv_utc - packet_ts) * 1000.0
            if channel in last_ts and rolling.values():
                delta = abs(owd_ms - rolling.values()[-1])
                jitter_ema += JITTER_ALPHA * (delta - jitter_ema)
            is_loss = False
            if channel in last_ts:
                gap = packet_ts - last_ts[channel]
                if gap > LOSS_THRESHOLD_S:
                    n_loss += max(0, round(gap / EXPECTED_INTERVAL_S) - 1)
                    is_loss = True
            last_ts[channel] = packet_ts
            n_received += 1
            rolling.add(recv_utc, owd_ms)
            records.append(PacketRecord(
                seq=seq, recv_utc=recv_utc, packet_ts=packet_ts, channel=channel,
                owd_ms=owd_ms, jitter_ms=jitter_ema, n_samples=len(samples),
                clock_offset_ms=clock_offset_ms, is_loss_gap=is_loss,
            ))
            seq += 1

        # Draw
        stdscr.erase()
        h, w = stdscr.getmaxyx()
        now     = time.time()
        elapsed = now - session_start
        stats   = rolling.compute()

        def safe(r, c, txt, attr=0):
            try:
                stdscr.addstr(r, c, txt, attr)
            except curses.error:
                pass

        row = 0
        safe(row, 0, '-' * w, C_TITLE); row += 1
        title = "  EEW SENSOR -- UDP LATENCY ANALYZER  "
        safe(row, max(0, (w - len(title)) // 2), title, C_TITLE); row += 1
        safe(row, 0, '-' * w, C_TITLE); row += 1

        dt_str = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
        safe(row, 2, f"Time: {dt_str}", C_LABEL)
        safe(row, 32, f"Elapsed: {elapsed:.0f}s", C_LABEL)
        safe(row, 48, f"Bind: {args.ip}:{args.port}", C_LABEL)
        if args.selftest:
            safe(row, 70, "[SELFTEST]", C_WARN)
        row += 1

        if clock_offset_ms is not None:
            col = C_WARN if abs(clock_offset_ms) > CLOCK_WARN_THRESHOLD_MS else C_GOOD
            safe(row, 2, f"NTP clock offset: {clock_offset_ms:+.2f} ms", col)
            if abs(clock_offset_ms) > CLOCK_WARN_THRESHOLD_MS:
                safe(row, 38, "WARNING -- OWD may be biased!", C_WARN)
        else:
            safe(row, 2, "NTP clock offset: unknown -- run w32tm /query /status", C_WARN)
        row += 1

        safe(row, 0, '-' * w, C_LABEL); row += 1
        safe(row, 2, "PACKET COUNTERS", C_TITLE); row += 1
        total     = n_received + n_loss
        loss_rate = (n_loss / total * 100) if total > 0 else 0.0
        loss_col  = C_ERR if loss_rate > 1.0 else (C_WARN if loss_rate > 0.1 else C_GOOD)
        safe(row, 4,  f"Received : {n_received}", C_GOOD)
        safe(row, 20, f"Lost : {n_loss}", loss_col)
        safe(row, 34, f"Loss: {loss_rate:.3f}%", loss_col)
        safe(row, 52, f"Rate: {n_received/max(elapsed,1):.1f} pkt/s", C_LABEL)
        row += 1

        safe(row, 0, '-' * w, C_LABEL); row += 1
        safe(row, 2, f"ONE-WAY DELAY  (rolling {ROLLING_WINDOW_S:.0f}s window)", C_TITLE); row += 1

        def vc(v, w2=200, e=500):
            return C_ERR if v > e else (C_WARN if v > w2 else C_GOOD)

        if stats['n'] >= 2:
            col_x = 4
            for lbl, val, wt, et in [('Mean', stats['mean'], 150, 300),
                                       ('Std',  stats['std'],   30,  80),
                                       ('Min',  stats['min'],   50, 150),
                                       ('Max',  stats['max'],  300, 600)]:
                txt = f"{lbl}: {val:8.2f} ms"
                safe(row, col_x, txt, vc(val, wt, et))
                col_x += len(txt) + 2
            row += 1
            col_x = 4
            for lbl, val, wt, et in [('P50', stats['p50'], 100, 250),
                                       ('P95', stats['p95'], 200, 400),
                                       ('P99', stats['p99'], 350, 600)]:
                txt = f"{lbl}: {val:8.2f} ms"
                safe(row, col_x, txt, vc(val, wt, et))
                col_x += len(txt) + 2
            row += 1
            safe(row, 4, f"Jitter (EWMA RFC3550): {jitter_ema:8.3f} ms", C_LABEL); row += 1
        else:
            safe(row, 4, "Waiting for packets...", C_WARN); row += 1

        safe(row, 0, '-' * w, C_LABEL); row += 1
        safe(row, 2, "OWD HISTOGRAM (last 60s)", C_TITLE); row += 1
        if stats['n'] >= 5:
            hist_w = min(w - 4, 70)
            vals   = rolling.values()
            clip   = np.percentile(vals, 99.5)
            bar_str, vmin, vmax = _build_histogram_bar(vals, width=hist_w, max_val=clip)
            safe(row, 4, bar_str, C_HIST); row += 1
            left = f"{vmin:.0f} ms"
            safe(row, 4, left, C_LABEL)
            right = f"{vmax:.0f} ms"
            safe(row, 4 + hist_w - len(right), right, C_LABEL); row += 1
        else:
            safe(row, 4, "Building histogram... (need >=5 packets)", C_LABEL); row += 1

        safe(row, 0, '-' * w, C_LABEL); row += 1
        safe(row, 2, "RECENT PACKETS", C_TITLE); row += 1
        safe(row, 4, f"{'SEQ':>6}  {'CH':5}  {'OWD_MS':>10}  {'JIT_MS':>10}  {'LOSS':5}", C_LABEL); row += 1
        for r in reversed(records[-10:]):
            if row >= h - 2:
                break
            ocol = C_ERR if r.owd_ms > 500 else (C_WARN if r.owd_ms > 200 else C_GOOD)
            safe(row, 4, f"{r.seq:>6}  {r.channel:5}  {r.owd_ms:>10.2f}  {r.jitter_ms:>10.3f}  ", ocol)
            if r.is_loss_gap:
                safe(row, 4 + 46, "YES", C_ERR)
            row += 1

        safe(h - 1, 0, ' Ctrl+C to stop and generate report ', C_TITLE)
        stdscr.refresh()
        time.sleep(0.1)
        key = stdscr.getch()
        if key == ord('q'):
            stop_event.set()


# ── Plain stdout logger ───────────────────────────────────────────────────────

def run_plain_logger(records, stop_event, rx_queue, args, session_start, clock_offset_ms):
    rolling    = RollingStats(ROLLING_WINDOW_S)
    jitter_ema = 0.0
    n_received = 0
    n_loss     = 0
    last_ts    = {}
    seq        = 0
    last_print = 0.0

    print(f"{'SEQ':>6}  {'CH':5}  {'OWD_MS':>10}  {'JIT_MS':>9}  {'P50':>8}  {'P95':>8}  LOSS")

    while not stop_event.is_set():
        try:
            recv_utc, raw = rx_queue.get(timeout=0.2)
        except queue.Empty:
            continue
        parsed = parse_eew_packet(raw)
        if parsed is None:
            continue
        channel, packet_ts, samples = parsed
        owd_ms = (recv_utc - packet_ts) * 1000.0
        if channel in last_ts and rolling.values():
            delta = abs(owd_ms - rolling.values()[-1])
            jitter_ema += JITTER_ALPHA * (delta - jitter_ema)
        is_loss = False
        if channel in last_ts:
            gap = packet_ts - last_ts[channel]
            if gap > LOSS_THRESHOLD_S:
                n_loss += max(0, round(gap / EXPECTED_INTERVAL_S) - 1)
                is_loss = True
        last_ts[channel] = packet_ts
        n_received += 1
        rolling.add(recv_utc, owd_ms)
        records.append(PacketRecord(
            seq=seq, recv_utc=recv_utc, packet_ts=packet_ts, channel=channel,
            owd_ms=owd_ms, jitter_ms=jitter_ema, n_samples=len(samples),
            clock_offset_ms=clock_offset_ms, is_loss_gap=is_loss,
        ))
        seq += 1
        now = time.time()
        if now - last_print >= 1.0:
            s = rolling.compute()
            print(f"{seq:>6}  {channel:5}  {owd_ms:>10.2f}  {jitter_ema:>9.3f}  "
                  f"{s['p50']:>8.2f}  {s['p95']:>8.2f}  {'LOSS' if is_loss else ''}")
            last_print = now


# ── UDP receiver thread ───────────────────────────────────────────────────────

def udp_receiver(port, bind_ip, rx_queue, stop_event):
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 1 << 20)
    except OSError:
        pass
    sock.bind((bind_ip, port))
    sock.settimeout(0.2)
    print(f"[UDP] Bound to {bind_ip}:{port}")
    while not stop_event.is_set():
        try:
            raw, addr = sock.recvfrom(8192)
            recv_utc  = time.time()
            rx_queue.put_nowait((recv_utc, raw))
        except socket.timeout:
            continue
        except OSError:
            break
    sock.close()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="EEW UDP Latency Analyzer -- scientific OWD measurement")
    parser.add_argument('--ip',          default='0.0.0.0')
    parser.add_argument('--port',        type=int, default=2098)
    parser.add_argument('--duration',    type=float, default=None)
    parser.add_argument('--window',      type=float, default=ROLLING_WINDOW_S)
    parser.add_argument('--selftest',    action='store_true')
    parser.add_argument('--no-dashboard', dest='no_dashboard', action='store_true')
    parser.add_argument('--output-dir',  default='.')
    args = parser.parse_args()

    print()
    print("=" * 60)
    print("  EEW UDP LATENCY ANALYZER -- Scientific Edition")
    print("=" * 60)
    print(f"  Bind     : {args.ip}:{args.port}")
    print(f"  Duration : {'unlimited (Ctrl+C to stop)' if args.duration is None else f'{args.duration:.0f}s'}")
    print(f"  Mode     : {'SELFTEST' if args.selftest else 'LIVE capture'}")
    print()
    print("  Checking NTP clock synchronization...", end='', flush=True)
    clock_offset_ms = get_ntp_offset_ms()
    if clock_offset_ms is not None:
        quality = "GOOD" if abs(clock_offset_ms) < CLOCK_WARN_THRESHOLD_MS else "WARNING"
        print(f" {clock_offset_ms:+.3f} ms  [{quality}]")
        if abs(clock_offset_ms) >= CLOCK_WARN_THRESHOLD_MS:
            print(f"  !! Clock offset > {CLOCK_WARN_THRESHOLD_MS:.0f} ms -- OWD will be biased!")
            print("     Fix: run 'w32tm /resync' or 'chronyc makestep'")
    else:
        print(" UNKNOWN (w32tm /query /status to check manually)")

    os.makedirs(args.output_dir, exist_ok=True)
    ts_str      = datetime.now().strftime('%Y%m%d_%H%M%S')
    csv_path    = os.path.join(args.output_dir, f"udp_latency_data_{ts_str}.csv")
    report_path = os.path.join(args.output_dir, f"udp_latency_report_{ts_str}.txt")
    fig_prefix  = os.path.join(args.output_dir, f"udp_latency_{ts_str}")

    print(f"\n  CSV    : {csv_path}")
    print(f"  Report : {report_path}")
    print()

    # Use a subclass of list so we can intercept append() to feed the CSV queue
    class RecordList(list):
        def __init__(self):
            super().__init__()
            self._csv_q = None
        def append(self, record):
            super().append(record)
            if self._csv_q is not None:
                try:
                    self._csv_q.put_nowait(record)
                except queue.Full:
                    pass

    records        = RecordList()
    rx_queue       = queue.Queue(maxsize=2000)
    stop_event     = threading.Event()
    session_start  = time.time()

    recv_thread = threading.Thread(
        target=udp_receiver,
        args=(args.port, args.ip, rx_queue, stop_event),
        daemon=True, name="udp-rx"
    )
    recv_thread.start()

    if args.selftest:
        threading.Thread(
            target=_selftest_sender,
            args=(args.port, stop_event),
            daemon=True, name="selftest-tx"
        ).start()
        time.sleep(0.3)

    if args.duration is not None:
        def _dur():
            time.sleep(args.duration)
            stop_event.set()
        threading.Thread(target=_dur, daemon=True).start()

    csv_fh, csv_writer_obj = open_csv(csv_path)
    csv_write_q = queue.Queue()

    def csv_loop():
        while not (stop_event.is_set() and csv_write_q.empty()):
            try:
                rec = csv_write_q.get(timeout=0.5)
                write_csv_row(csv_writer_obj, rec)
                csv_fh.flush()
            except queue.Empty:
                pass
        csv_fh.close()

    csv_thread = threading.Thread(target=csv_loop, daemon=True, name="csv-writer")
    csv_thread.start()

    records._csv_q = csv_write_q

    try:
        if not args.no_dashboard and _CURSES_AVAILABLE:
            import curses
            curses.wrapper(run_dashboard, records, stop_event, rx_queue,
                           args, session_start, clock_offset_ms)
        else:
            if not _CURSES_AVAILABLE and not args.no_dashboard:
                print("  curses unavailable -- plain stdout mode.")
                print("  Install 'windows-curses' for full dashboard: pip install windows-curses")
            run_plain_logger(records, stop_event, rx_queue, args, session_start, clock_offset_ms)
    except KeyboardInterrupt:
        stop_event.set()

    stop_event.set()
    session_end = time.time()
    recv_thread.join(timeout=2)
    csv_thread.join(timeout=5)

    plain_records = list(records)
    print()
    print("=" * 60)
    print("  SESSION COMPLETE -- Generating outputs...")
    print("=" * 60)
    print(f"  Total packets : {len(plain_records)}")

    if plain_records:
        generate_text_report(plain_records, session_start, session_end, report_path, args)
        generate_figures(plain_records, session_start, session_end, fig_prefix)
    else:
        print("  No packets received!")
        print("  - Check the sensor is running and configured with this PC's IP over ZeroTier.")
        print("  - Try: python udp_latency_analyzer.py --selftest")

    print(f"\n  CSV    : {csv_path}")
    print(f"  Report : {report_path}")
    print()


if __name__ == '__main__':
    main()
